minijail: reduce build warnings/errors
When building minijail externally, several warnings (and an error) are
present. This fixes them and adds myself to the OWNERS file, since I
review a lot of minijail commits anyway.

Warning due to common.mk:

$ make LIBDIR=/tmp
cat: /home/kees/src/minijail/../common-mk/BASE_VER: No such file or directory
Using BASE_VER=
cd "/home/kees/src/minijail/" && make -r -I "/home/kees/src/minijail" -f "/home/kees/src/minijail/Makefile" SRC="/home/kees/src/minijail" OUT="/home/kees/src/minijail/" "all"
make[1]: Entering directory '/home/kees/src/minijail'
cat: /home/kees/src/minijail/../common-mk/BASE_VER: No such file or directory
Using BASE_VER=
...

Instead, define the (unused) BASE_VER before including common.mk.

Error with recent GCC snapshots:

/home/kees/src/minijail/syscall_filter.c: In function 'compile_errno':
/home/kees/src/minijail/syscall_filter.c:266:6: error: '__s' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if (errno_val_ptr == errno_val_str || errno_val == -1) {
      ^
cc1: all warnings being treated as errors

This turns out to be a (long-standing??) bug in GCC (triggered in
this case by -O2 for some reason), but it's easy enough to work
around. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55985

Bug: None
Test: Build
Change-Id: Idd4320f0f18791201e06ee6bda6f2c76653b6df9